#!/usr/bin/env bash

# git add .  
# git commit -m 'testing'
# git push -f
# curl -L is.gd/arcrisnew > arcris ; sh arcris 

echo ""
echo "es_ES.UTF-8 UTF-8" > /etc/locale.gen
locale=$(locale-gen)
dialog --stdout --infobox "$locale" 10 50
echo "LANG=es_ES.UTF-8" > /etc/locale.conf
export LANG=es_ES.UTF-8
clear

welcome_title=" | Selector de idioma|"


cmd=(dialog --nocancel --backtitle "Bienvenido/a : $(date "+%A, %B %d, %Y - %I:%M %p")" --title "${welcome_title}" \
    --menu "\nDonaciones en\nwww.patreon.com/codigocristo\npaypal.me/sebasdark156\n\n---------------------------------------------\n\nSeleccione el idioma del instalador:\n\n " 20 90 20)

options=(1. "Español")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in


        1.)
        source languages/español.conf
        echo "$LANGUAGE UTF-8" > /etc/locale.gen
        locale=$(locale-gen)
        dialog --backtitle "$title" \
        --title "${idiom}" --stdout --ok-label "${oklabel}" \
        --infobox "$locale" 10 50
        echo "LANG=$LANGUAGE" > /etc/locale.conf
        export LANG=$LANGUAGE
        setfont lat5-16
        ;;

    esac
done





sectionuser=0
sectionubi=0
sectionlang=0
sectionshell=0
sectiondisk=0
sectionkernel=0
sectionvideo=0
sectionenv=0

main () {

while true; do



menuprincipal=(dialog --keep-tite --default-item "${current_item}" --backtitle "${title}" --title "${title_menu}" \
--ok-label "${select_ok_label}" --nocancel --no-tags \
--menu "${text_menu}" ${highmenu} ${widthmenu} 12)

options=(   1 "${menu1} ${submenu1}" 
            2 "${menu2} ${submenu2}" 
            3 "${menu3} ${submenu3}" 
            4 "${menu4} ${submenu4}" 
            5 "${menu5} ${submenu5}" 
            6 "${menu6} ${submenu6}" 
            7 "${menu7} ${submenu7}" 
            8 "${menu8} ${submenu8}" 
            9 "${menu9} ${submenu9}" 
            10 "${menu10} ${submenu10}"
            11 "${menu11} ${submenu11}"  )

choices=$("${menuprincipal[@]}" "${options[@]}" 2>&1 >/dev/tty)


for choice in $choices
do
    case $choice in

1)
source lib/user #Hecho
users
clear
current_item="2"
;;

2) 
source lib/zoneinfo #Hecho
locality
current_item="3"
;;


3)
source lib/lang #Hecho
lang
current_item="4"
;;

4) 
source lib/shellsystem #Hecho
shellsystem
current_item="5"
;;

5)
source lib/disks #Hecho
disksystem
current_item="6"
;;

6)
source lib/kernel #Hecho
kerneles
current_item="7"
;;

7)
source lib/video #Hecho
drivervideo
;;

8)
source lib/environment #Hecho
environment
current_item="9"
;;

9)
source lib/extras #Hecho
extraprogram
current_item="10"
;;

10)
source lib/install #Hecho
install

;;

11)
cd 
rm -r arcris arcris-modyfied-master arcris-modyfied-master.tar.gz
clear && echo "" 
echo -e ""
echo -e "${msg_end}"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
echo "" && sleep 3 && clear && setfont default8x16 && exit
;;

    esac
done


    
done

}

main
# Codigo cristo pal mundo








