#!/bin/bash


fuc_utilidades () {

#UTILIDADES
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}"  \
--no-tags --ok-label ' Confirm ' --cancel-label ' Cancel' --checklist "Utilities for your new installation\nUse [SPACE] for check or uncheck (*)" 22 80 22)
options=(1 "Read/Write on disks (Android included)" on    # any option can be set to default to "on"
         2 "Compress/Decompress of files" on
         3 "Video codecs and media players" off
         4 "gufw - Network firewall" off
         5 "hardinfo - System info and benchmark" off
         6 "gnome-disk-utility - Disk manager" off
         7 "gparted - Partition Manager" off
         8 "yt-dlp - YouTube client" off
         9 "viewnior - Images gallery" off
         10 "gedit - GTK Text editor" off
         11 "Flatpak - GNU/Linux application sandboxing" off
         12 "Qemu - Emulator and machines virtualizator SDL" off
         13 "VirtualBox - Virtual machines manager" off
         14 "Visual Studio Code - Source code editor" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
1)
UTIL1=true
;;

2)
UTIL2=true
;;

3)
UTIL3=true
;;

4)
UTIL4=true
;;

5)
UTIL5=true
;;

6)
UTIL6=true
;;

7)
UTIL7=true
;;

8) 
UTIL8=true
;;

9)
UTIL9=true
;;   

10)
UTIL10=true
;;


11)
UTIL11=true
;; 

12)
UTIL12=true
;; 

13)
UTIL13=true
;;

14)
UTIL14=true
;;

    esac
done
#FINAL DE UTILIDADES

}


fuc_terminales () {

#TERMINALES
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}"  \
--no-tags --ok-label ' Confirm ' --cancel-label ' Cancel' --checklist "Terminal for your system\nUse [SPACE] for check or uncheck (*)" 17 80 17)
options=(1 "lxterminal - LXDE/LXQt default terminal" off    # any option can be set to default to "on"
         2 "tilix" off
         3 "xfce4-terminal - XFCE4 default terminal" off
         4 "deepin-terminal - Deepin default terminal" off
         5 "mate-terminal - Mate default terminal" off
         6 "terminator" off
         7 "st" off
         8 "alacritty" off
         9 "kitty" off
         10 "gnome-terminal - Gnome/Cinnamon default terminal" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            TERMI1=true
            ;;
        2)
            TERMI2=true
            ;;
        3)
            TERMI3=true
            ;;
        4)
            TERMI4=true
            ;;
        
        5)
            TERMI5=true
            ;;

        6)
            TERMI6=true
            ;;
               
        7)
            TERMI7=true
            ;;   
        8)
            TERMI8=true
            ;;   
        9)
            TERMI9=true
            ;;
        10)
            TERMI10=true
            ;;
    esac
done
#FINAL DE TERMINALES
}


fuc_audiosistema () {

#AUDIO
cmd=(dialog --no-collapse --cr-wrap --title "|System's Audio|" --backtitle "${title}"  \
--no-tags --ok-label ' Confirm ' --cancel-label ' Cancel' --radiolist "\n- Pulseaudio for the classic user \
\n- Jackaudio without latency for professionals \
\n- Alsaaudio for terminal without GUI \
\n- PipeWire Audio for the future in sound\n \
\nUse [SPACE] for check (*)" 17 80 17)
options=(1 " PipeWire   + Audio codecs  " off    # any option can be set to default to "on"
         2 " Pulseaudio + Audio codecs   " off
         3 " Jack2      + Audio codecs   " off
         4 " ALSA       + Audio codecs   " off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in

        1)
            AUDIO1=true
            # https://wiki.archlinux.org/title/PipeWire
            ;;

        2)
            AUDIO2=true
            # https://wiki.archlinux.org/index.php/PulseAudio
            # pulseeffects libcanberra-pulse libcanberra-gstreamer 
            ;;

        3)
            AUDIO3=true
            #https://wiki.archlinux.org/index.php/Professional_audio
            ;;

        4)
            AUDIO4=true
            #https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture
            ;;

    esac
done
#FIN_AUDIO

}



fuc_reproductores () {

#REPRODUCTOR

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label ' Confirm ' --cancel-label ' Cancel' \
--title "|Video and Audio players|" \
--checklist "\nUse [SPACE] for check or uncheck (*)" 15 80 15)
options=(   1 " vlc                           " off
            2 " mpv                           " off
            3 " nuclear-player-bin            " off            
            4 " spotify-noads-adblock         " off
            5 " audacious                     " off
            6 " moc                           " off
            7 " cmus                          " off
            8 " celluloid                     " off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            REPRO1=true
            ;;
        2)
            REPRO2=true
            ;;
        3)
            REPRO3=true
            ;;
        4)
            REPRO4=true
            ;;
        5)
            REPRO5=true
            ;;
        6)
            REPRO6=true
            ;;
        7)
            REPRO7=true
            ;;
        8)
            REPRO8=true
            ;;
    esac
done

# FIN REPRODUCTOR

}



fuc_navegador_web () {

#NAVEGADORES
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label ' Confirm ' --cancel-label ' Cancel' --checklist "Select your web browser\nUse [SPACE] for check or uncheck (*)" 16 80 16)
options=(1 "Firefox - Mozilla Firefox full version" off    # any option can be set to default to "on"
         2 "Chromium - Google Chrome open source version" off
         3 "Midori - GTK and Webkit based lightweight browser" off
         4 "Brave - Chromium and Web3 based browser" off
         5 "Google Chrome - Google Inc. browser" off
         6 "Opera - Opera Software browser" off
         7 "Vivaldi - Opera (2015) based browser" off
         8 "Tor - Proxificated browser" off
         9 "Firefox-ESR - Mozilla Firefox lightweight version" on
         10 "Microsoft Edge - Windows web browser" off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            WEB1=true
            ;;
        2)
            WEB2=true
            ;;
        3)
            WEB3=true
            ;;
        4)
            WEB4=true
            ;;
        5)
            WEB5=true
            ;;
        6)
            WEB6=true
            ;;
        7)
            WEB7=true
            ;;
        8)
            WEB8=true
            ;;
        9)
            WEB9=true
            ;;
        10)
            WEB10=true
            ;;
    esac
done
# FIN NAVEGADORES

}




fuc_ofimatica () {

#OFFICE
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --title "|Office Tools|"\
--no-tags --ok-label ' Confirm ' --cancel-label ' Cancel' --checklist "Select your Ofimatic Environment\nUse [SPACE] for check or uncheck (*)\n " 12 80 12)
options=(    1 "LibreOffice - Open source Office tools" off
             2 "WPS Office - Office tools like MS-Office" off
             3 "SoftMaker Office - like MS-Office open source " off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            OFFICE1=true
            ;;
        2)
            OFFICE2=true
            ;;
        3)
            OFFICE3=true
            ;;
    esac
done
# FIN OFFICE

}



fuc_administrador_de_tareas () {

#Administrador de Tareas
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --title "|Task Manager|" \
--no-tags  --ok-label ' Confirm ' --cancel-label ' Cancel' --checklist "Select a Task Manager for your system\nUse [SPACE] for check or uncheck (*)\n " 14 80 14)
options=(1 " gnome-system-monitor " off
         2 " htop                 " on
         3 " bashtop              " off
         4 " gtop                 " off
         5 " gotop - AUR          " off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            AP1=true
            ;;
        2)
            AP2=true
            ;;
        3)
            AP3=true
            ;;
        4)
            AP4=true
            ;;
        5)
            AP5=true
            ;;
            
            
    esac
done



}



fuc_social () {

#Redes Sociales
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}"  --title "| Social Media |" \
--no-tags  --ok-label ' Confirm ' --cancel-label ' Cancel' --column-separator "|" --checklist "\nUse [SPACE] for check or uncheck (*)\n " 15 80 20)
options=(1 "Telegram - Instant Messaging" on
         2 "IGdm - Instagram chat app" off
         3 "Whatsapp - Whatsapp client" off
         4 "Facebook Messenger - Meta MSN client" off
         5 "Netflix - Non-official app for Linux" off
         6 "Skype - Microsoft Messaging" off
         7 "Discord - Instant IRC Messaging" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            RS1=true
            ;;
        2)
            RS2=true
            ;;
        3)
            RS3=true
            ;;
        4)
            RS4=true
            ;;    
        5)
            RS5=true
            ;;            
        6)
            RS6=true
            ;;

        7)
            RS7=true
            ;;

    esac
done
#FINAL DE Redes Sociales

}


fuc_gamer () {

#INICIO DE GAMING
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}"  --title "| Gaming |" \
--no-tags  --ok-label ' Confirm ' --cancel-label ' Cancel' --column-separator "|" --checklist "\nUse [SPACE] for check or uncheck (*)\n " 24 80 24)
options=(1 "steam | Developed by Valve platform" off
         2 "wine | Windows applications on Linux excecutor" off
         3 "crossover | Wine pay to use" off
         4 "winetricks | Wine configurator for install libraries" off
         5 "lutris | Games installer" off
         6 "legendary | like Epic Games Launcher open source app" off
         7 "retroarch | A big platform with emulators, frameworks and players" off
         8 "snes9x-gtk | SuperNES Emulator" off
         9 "ppsspp | PlayStation Portable Emulator" off
         10 "pcsx2 | PlayStation 2 Emulator" off
         11 "rpcs3 | PlayStation 3 - Emulator" off
         12 "cemu | Nintendo Wii U Emulator (via wine)" off
         13 "citra-git | Nintendo 3DS Emulator" off
         14 "desmume | Nintendo DS Emulator" off
         15 "higan | SNES, NES, GB, GBC, GBA Emulator" off
         16 "yuzu | Nintendo Switch Emulator" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            GAM1=true
            ;;
        2)
            GAM2=true
            ;;
        3)
            GAM3=true
            ;;
        4)
            GAM4=true
            ;;    
        5)
            GAM5=true
            ;;            
        6)
            GAM6=true
            ;;
        7)
            GAM7=true
            ;; 
        8)
            GAM8=true
            ;;
        9)
            GAM9=true
            ;; 
        10)
            GAM10=true
            ;; 
        11)
            GAM11=true
            ;;
        12)
            GAM12=true
            ;;
        13)
            GAM13=true
            ;;
        14)
            GAM14=true
            ;;    
        15)
            GAM15=true
            ;;
        16)
            GAM16=true
            ;;

    esac
done

#FINAL DE GAMING
}




fuc_aur_helpers () {

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}"  --title "| AUR Installers |" \
--no-tags  --ok-label ' Confirm ' --cancel-label ' Cancel' --column-separator "|" --checklist "\nUse [SPACE] for check or uncheck (*)\n " 19 80 19)
options=(1 "yay | Terminal" on
         2 "trizen | Terminal" off
         3 "pikaur | Terminal" off
         4 "aurman | Terminal" off
         5 "pakku | Terminal" off
         6 "Pamac | Graphical" off
         7 "Octopi | Graphical" off
         8 "Cylon | Graphical" off
         9 "Argon | Graphical" off
         10 "Pakku GUI | Graphical" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            AUR1=true
            ;;
        2)
            AUR2=true
            ;;
        3)
            AUR3=true
            ;;
        4)
            AUR4=true
            ;;    
        5)
            AUR5=true
            ;;            
        6)
            AUR6=true
            ;;
        7)
            AUR7=true
            ;; 
        8)
            AUR8=true
            ;;
        9)
            AUR9=true
            ;; 
        10)
            AUR10=true
            ;; 

    esac
done

#FINAL DE AUR

}




extraprogram () {


extraprograms=true

AP_condicion=false
TERMINAL_condicion=false

while [[ $extraprograms == "true" ]]; do

menuextras=$(dialog --keep-tite --backtitle "${title}" --title "| Extra Packages |" \
--ok-label "Select" --default-item "${extras_item}" --no-tags \
--menu "\nSelect the extra packages do you prefer      \n " 20 60 10 \
1 "               Utilities                             " \
2 "               Terminals                             " \
3 "               Audio                                 " \
4 "               Players                               " \
5 "               Web Browsers                          " \
6 "               Office Tools                          " \
7 "               Task Managers                         " \
8 "               Social media                          " \
9 "               Gaming                                " \
10 "              AUR Installers                        " \
11 "        [ Save your selection to install ]          " 3>&1 1>&2 2>&3)

case "$menuextras" in

"1")
fuc_utilidades
extras_item="2"
;;

"2") 
fuc_terminales
extras_item="3"
;;

"3")
fuc_audiosistema
extras_item="4"
;;

"4") 
fuc_reproductores
extras_item="5"
;;

"5")
fuc_navegador_web
extras_item="6"
;;

"6")
fuc_ofimatica
extras_item="7"
;;

"7")
fuc_administrador_de_tareas
extras_item="8"
;;

"8")
fuc_social
extras_item="9"
;;

"9")
fuc_gamer
extras_item="10"
;;

"10")
fuc_aur_helpers
extras_item="11"
;;

"11")
extraprograms=false
break
;;

$1)  # BOTON CANCELAR
extraprograms=false
break
;;

    esac
done


}


