#!/bin/bash

kerneles () {

### KERNEL 
selecLinuxStable=false
selecLinuxHard=false
selecLinuxLts=false
selecLinuxZen=false

microdriver=false
wifidriver=false
wifidriverdmks=false
touchdriver=false
blutudriver=false

selec8168=false
selec8168lts=false

kernel_var=0 



while [ "$kernel_var" = "0" ] ; do

kernel_select=$(dialog --backtitle "${title}" --title "| Núcleo |" \
--stdout --ok-label "Selecciona" --no-cancel --menu "\nElige que núcleo necesitas: \n\n\
> Linux Estable es la mejor opción\n\nLas otras opciones tienen un estilo diferente para \
instalar los controladores\nLas otras versiones del núcleo trabajan con controladores libres\n " 18 0 200 \
"linux-stable"  " La imagen genérica y estable más reciente de Linux" \
"linux-hardened"  " Núcleo con endurecimiento para proporcionar mayor seguridad " \
"linux-lts"  " Núcleo con soporte de larga duración                    " \
"linux-zen"  " Versión de Liquorix para Archlinux ")

#####Stable  
  if [ $kernel_select == linux-stable ]; then
##################################################################################
r8168=$(arch-chroot /mnt /bin/bash -c "lspci -k | grep 'RTL8111/8168/8411' ")

if [[ $r8168  = *RTL8111/8168/8411* || $r8168 = *Rtl8111/8168/8411* || $r8168 = *rtl8111/8168/8411* ]]
then      
selec8168=true
fi

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label "Aceptar" --cancel-label "Cancelar" --title " | Módulos para el núcleo |" --checklist "Seleccione los modulos que necesita \nUse [ESPACIO] para marcar o desmarcar (*)" 11 110 10)
options=(1 " Módulo para el Wi-fi              "          off  # any option can be set to default to "on"
         2 " Módulo para el panel táctil de las Laptops " off
         3 " Módulo para el Bluetooth          "          off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1) wifidriver=true
        ;; 
        2) touchdriver=true
        ;;
        3) blutudriver=true
        ;;
    esac
done

  selecLinuxStable=true
  kernel_var=1


#####hardened
  elif [ $kernel_select == linux-hardened ]; then

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label "Aceptar" --cancel-label "Cancelar" --title " | Módulos para el núcleo |" --checklist "Seleccione los modulos que necesita \nUse [ESPACIO] para marcar o desmarcar (*)" 11 110 10)
options=(1 " Módulo para el Wi-fi              "          off  # any option can be set to default to "on"
         2 " Módulo para el panel táctil de las Laptops " off
         3 " Módulo para el Bluetooth          "          off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1) wifidriverdmks=true
        ;; 
        2) touchdriver=true
        ;;
        3) blutudriver=true
        ;;
    esac
done

  selecLinuxHard=true
  kernel_var=1



######LTS
  elif [ $kernel_select == linux-lts ]; then
##################################################################################
r8168=$(arch-chroot /mnt /bin/bash -c "lspci -k | grep 'RTL8111/8168/8411' ")
if [[ $r8168  = *RTL8111/8168/8411* || $r8168 = *Rtl8111/8168/8411* || $r8168 = *rtl8111/8168/8411* ]]
then      
selec8168lts=true
fi

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label "Aceptar" --cancel-label "Cancelar" --title " | Módulos para el núcleo |" --checklist "Seleccione los modulos que necesita \nUse [ESPACIO] para marcar o desmarcar (*)" 11 110 10)
options=(1 " Módulo para el Wi-fi              "          off  # any option can be set to default to "on"
         2 " Módulo para el panel táctil de las Laptops " off
         3 " Módulo para el Bluetooth          "          off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1) wifidriverdmks=true
        ;; 
        2) touchdriver=true
        ;;
        3) blutudriver=true
        ;;
    esac
done
  
  selecLinuxLts=true
  kernel_var=1  


###### ZEN
  elif [ $kernel_select == linux-zen ]; then
##################################################################################

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label "Aceptar" --cancel-label "Cancelar" --title " | Módulos para el núcleo |" --checklist "Seleccione los modulos que necesita \nUse [ESPACIO] para marcar o desmarcar (*)" 11 110 10)
options=(1 " Módulo para el Wi-fi              "          off  # any option can be set to default to "on"
         2 " Módulo para el panel táctil de las Laptops " off
         3 " Módulo para el Bluetooth          "          off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1) wifidriverdmks=true
        ;; 
        2) touchdriver=true
        ;;
        3) blutudriver=true
        ;;
    esac
done
   
  selecLinuxZen=true
  kernel_var=1
  
  
  fi
done

sectionkernel=1

}






demomicrocode () {

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label "Aceptar" --cancel-label "Cancelar" --title " | Módulos para el núcleo |" --checklist "Seleccione los modulos que necesita \nUse [ESPACIO] para marcar o desmarcar (*)" 11 110 10)
options=(1 " Actualizaciones del Microcode  "            on    # any option can be set to default to "on"
         2 " Módulo para el Wi-fi              "         off
         3 " Módulo para el panel táctil de las Laptops" off
         4 " Módulo para el Bluetooth           "        off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1) microdriver=true
        ;; 
        2) wifidriver=true
        ;; 
        3) touchdriver=true
        ;;
        4) blutudriver=true
        ;;
    esac
done

}
